services:

  # Kafka config comes from the resourses given during course
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    healthcheck:
      test: nc -z localhost 2181 || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:29092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 10
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "28080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - ./kafka-ui-config.yml:/etc/kafkaui/dynamic_config.yaml

  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./redis-data:/data

  webhook:
    image: balanse/webhook
    build:
      context: ./webhook
      dockerfile: Dockerfile
    ports:
      - 3337:3337
    depends_on:
      redis:
        condition: service_started
      kafka:
        condition: service_healthy
  
  quarkus:
    image: balanse/server-quarkus
    build:
      context: ./server-quarkus
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - 8080:8080
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started

  dashboard:
    image: balanse/dashboard
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - quarkus

networks:
  balanse:
    driver: bridge
